[all:vars]
ansible_ssh_pass=Root!234
ansible_sudo_pass=Root!234
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_ssh_user=pgtalk
ansible_become = True
ssh_args = -o ControlMaster=auto -o ControlPersist=60s
host_key_checking=False
validate_certs=False

[nfs-client]
10.1.23.44
10.1.23.45
10.1.23.46
10.1.23.47
10.1.23.48
