user: 
pass: 

nfs:
  server:
    ip: 10.1.23.53
    path: /mnt/pgtalk
  client:
    ip:
    - 10.1.23.44
    - 10.1.23.45
    - 10.1.23.46
    - 10.1.23.47
    - 10.1.23.48

drbd:
  primary:
    ip: 10.1.23.53 
    hostname: drbd1
  secondary: 
    hostname:
    - drbd2
    ip:
    - 10.1.23.54
  disk:
    path: /dev/sdb
    size: 100GB
    mount: /mnt/pgtalk
  fstype: xfs

k8s:
- master: 10.1.23.41
- master: 10.1.23.42
- master: 10.1.23.43
- worker: 10.1.23.44
- worker: 10.1.23.45
- worker: 10.1.23.46
- worker: 10.1.23.47
- worker: 10.1.23.48  

docker:
  requried_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  docker_engines:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  ip:
  - 10.1.23.41
  - 10.1.23.42
  - 10.1.23.43
  - 10.1.23.44
  - 10.1.23.45
  - 10.1.23.46
  - 10.1.23.47
  - 10.1.23.48
