user: YOUR_LOGIN_USER
pass: YOUR_LOGIN_PASS
deploy: DEPLOY_NODE_IP

cicd: CICD_NODE_IP

k8s:
  - master: K8S_MASTER_NODE_IP
  - worker: K8S_WORKER_NODE_IP
haproxy:
  - haproxy: FIRST_HAPROXY_NODE_IP
  - haproxy: SECOND_HAPROXY_NODE_IP
  - vip: K8S_VIP

drbd:
  primary:
    ip: 10.1.23.53
    hostname: drbd1
  secondary:
    hostname:
    - drbd2
    ip:
    - 10.1.23.54
  disk:
    path: /dev/sdb
    size: 100GB
    mount: /mnt/pgtalk
  fstype: xfs
