user: YOUR_LOGIN_USER
pass: YOUR_LOGIN_PASS
deploy: DEPLOY_NODE_IP

cicd: CICD_NODE_IP

k8s:
  - master: K8S_MASTER_NODE_IP
  - worker: K8S_WORKER_NODE_IP
haproxy:
  - haproxy: FIRST_HAPROXY_NODE_IP
  - haproxy: SECOND_HAPROXY_NODE_IP
  - vip: K8S_VIP

nfs:
  - master: NFS_MASTER_NODE_IP
  - slave: NFS_SLAVE_NODE_IP
